### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by majidb** [fred4jupiter/fredbet#1]
Hi,
Some .html template files are not fully internationnalized,
for example :

list.html :
`
<title>Spiele</title>
`

form.html ...
Länderauswahl
oder Teamnamen
...

Can I contribute ?

Best Regards,
Majid

**Comment by fred4jupiter** [comment]
You are right. That´s on ToDo list. But you can contribute. You´re welcome.

Best regards,

Michael

**Comment by fred4jupiter** [comment]
Hi Majid, 

I´ve finished the i18n ToDo´s. The application is now fully internationalized. Only german and english is available by now. You can contribute other languages if you like. All translations are located in the message bundle (like messages_en.properties).

Best regards,

Michael
