### ISSUE TITLE
[feature request] Add view with group standings

### ISSUE THREAD

**Issue by bartektartanus** [fred4jupiter/fredbet#14]
Just like here:
https://www.flashscore.com/football/world/world-cup/standings/?t=fFsiH75r&ts=OneVXSrp

additionally after group phase is completed, playoff matches teams could be automatically set.

**Comment by fred4jupiter** [comment]
I thought about that. But just for the betting it´s not really necessary. I will leave it open for now. Maybe it will be implemented in the future.

**Comment by fred4jupiter** [comment]
simple standings table added in version 2.4.0

**Comment by fred4jupiter** [comment]
Currently first version in 2.4.0-SNAPSHOT (docker version 'latest'). Stable release will be 2.4.0
