### ISSUE TITLE
docker-compose isnt working

### ISSUE THREAD

**Issue by WinstonAcid** [fred4jupiter/fredbet#2]
This compose file isnt working with your latest docker release fredbet/src/docker/docker-compose/mysql.yml

If i change image to fred4jupiter/fredbet:2.0.0 then its working

**Comment by fred4jupiter** [comment]
Yes, you´re right. I forgot to change the database properties in the compose files. Now it´s fixed. Please try again.

**Comment by fred4jupiter** [comment]
docker compose files are fixed.
