### ISSUE TITLE
Password change does not allow passwords longer than 12 chars

### ISSUE THREAD

**Issue by trigrab** [fred4jupiter/fredbet#26]
I think when allowing longer passwords, these lines were forgotten.
https://github.com/fred4jupiter/fredbet/blob/4a1f61b53a78b00069dcc49190f633c438a9ff89/src/main/java/de/fred4jupiter/fredbet/web/profile/ChangePasswordCommand.java#L15

https://github.com/fred4jupiter/fredbet/blob/4a1f61b53a78b00069dcc49190f633c438a9ff89/src/main/java/de/fred4jupiter/fredbet/web/profile/ChangePasswordCommand.java#L19

Thanks  for this wonderful project :)

**Comment by fred4jupiter** [comment]
Yes, I fixed that yesterday. It's 100 char now. Please check latest version. It's not in the released version by now.

**Comment by fred4jupiter** [comment]
Ah, sorry. You are right. That's I've been forgotten. I will fix that asap.

**Comment by fred4jupiter** [comment]
Corrected with 65db80fa5913ec1f6ebab2a07299d89533810883
