### ISSUE TITLE
1Bug 2 Feature requests

### ISSUE THREAD

**Issue by sunnybeats** [fred4jupiter/fredbet#28]
Hey,

i used fredbet for em2021 and i have to say its a very nice little software. Thank you for sharing it.

The Bug:
i found 1 thing that‘s not working correctly.

if you use the „roll for all games“ function, you are able to roll for a Contest winner even after the contest started already

Featue 1:

is it possible caclulate the K.O. Matches automatically?

Feature 2:

it would be nice to be able to export all tipps auf all player at the end of the Contest.

Thank you!

**Comment by fred4jupiter** [comment]
Can you give more details about the bug you mention? How can I reproduce it?

About feature 1: This might be possible but is not on the roadmap for now.

About feaure 2: You can export the tipps and bets of all players to MS Excel. Go to Admin -> Excel Export. Is this what you are looking for?

Best regards, 
Michael

**Comment by sunnybeats** [comment]
Also vom Namen her vermute ich mal, dass ich auch auf deutsch schreiben kann.

was uns aufgefallen war:

Dar wir das Tippen leider bei bereits laufender Em erst begonnen hatten, konnten wir keine Tipps für den Europameister und Vize-Meister mehr abgeben. (Was uns logisch erschien)

wenn ich aber die Funktion „alle spiele würfeln“ benutzt habe, wurden die Meister und Vize-Meister automatisch auch als tipps gewürfelt, obwohl man es manuell bereits nicht mehr konnte.

**Comment by fred4jupiter** [comment]
Ah, ok. Danke für den Hinweis. Vielleicht ist da noch ein Fehler drin. Schau ich mir mal an.

**Comment by sunnybeats** [comment]
Der Punkt mit dem Excel export passt bestens,  hatte ich übersehen.

Eine idee hätte ich noch für den 2. Punkt.

ich kann verstehen, dass es entsprechend aufwendig ist den Code so anzupassen, dass die Berechnung der Begegnungen automatisch ermittelt wird. Ich fände es aber Sinnvoll, wenn es eine Möglichkeit gäbe jemanden die Möglichkeit zu geben, die Paarungen einzutragen ohne dafür gleich Admin rechte haben zu müssen.


Sprich:


Entweder dem der die Spielergebnisse eintragen darf auch die rechte geben die Teams einzutragen oder:

was ich noch besser fände eine eigene Rechtegruppe die Ergebnisse + Teams pflegen darf.


Soll heißen:


1 Gruppe Ergebnisse eintragen
1 Gruppe Ergebnisse + Teams

und dann erst die Admins

Wenn es nicht umgesetzt wird, kann ich das auch verstehen. Alles in allem eine tolle, gelungene Software. 
Haben es gerne genutzt und ich werden es bestimmt zur nächsten Meisterschaft wieder tun.

Grüße


Marcell

**Comment by fred4jupiter** [comment]
Hallo Marcell, ja, das gibt es. Das sind genau die 4 Rollen in der Benutzeradministration:

1. Normaler Benutzer
2. Normal + Eingabe Ergebnisse
3.  Normal + Eingabe Ergebnisse + Match bearbeiten und Benutzer anlegen
4.  Admin Benutzer (darf alles)

Aus der Beschreibung geht allerdings nicht so genau hervor, dass Rolle 3 auch Teams bearbeiten kann. Also z.B. die K.O. Runde konfigurieren.

Am Besten mal mit Rolle 3 testen.

VG

**Comment by fred4jupiter** [comment]
Ich schließe das Ticket mal, da die Gruppen ja vorhanden sind und das Zielverhalten so abbildbar ist.
