### ISSUE TITLE
Final match bets bug

### ISSUE THREAD

**Issue by bartektartanus** [fred4jupiter/fredbet#29]
![image](https://user-images.githubusercontent.com/3193882/125261830-ec11e400-e301-11eb-8b34-de01f8921636.png)

As you can see, users get points for correctly predicting winner of the match (1 point) but it has never been that way before:

![image](https://user-images.githubusercontent.com/3193882/125262024-1a8fbf00-e302-11eb-9d7b-bfffff54e83c.png)

Now it looks like it gives point for predicting the winner (after resave of the game result) but only if the home team is winning:

1) 1 point and home team won in penalty
![image](https://user-images.githubusercontent.com/3193882/125262497-84a86400-e302-11eb-9664-2e56e0e7cd17.png)
2) 0 points and away team won
![image](https://user-images.githubusercontent.com/3193882/125262627-9f7ad880-e302-11eb-81e8-36acdebcd709.png)

**Comment by fred4jupiter** [comment]
Yes, this was a bug. It is now fixed in lastest version. Thanks for pointing out!
