### ISSUE TITLE
Update WM2018.xlsx

### ISSUE THREAD

**Issue by user121216** [fred4jupiter/fredbet#3]
Hey,

can you pls change Austria to Australia. :)

I also checked the kick off dates. Here some diffs:

COSTA_RICA vs. SERBIA is at 14:00 instead of 20:00
BRAZIL vs. SWITZERLAND is at 20:00 instead of 14:00
DENMARK vs. AUSTRALIA is at 14:00 instead of 17:00
FRANCE vs. PERU is at 17:00 instead of 14:00

Sieger B vs. Zweiter A is at 16:00 instead of 18:00

Thanks a lot & Happy to bet!

**Comment by fred4jupiter** [comment]
Thanks for your help. I fixed the template :-)
