### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by Jotiprime** [fred4jupiter/fredbet#31]
When copy the repository to your directory and then run the <mvn install spring-boot:run> command, appears java error!

![Captura de pantalla 2022-03-12 021522](https://user-images.githubusercontent.com/73477224/157997662-4658bfe6-65c9-4549-80ec-fa26f1a28564.png)

**Comment by Jotiprime** [comment]
![Captura de pantalla 2022-03-12 021746](https://user-images.githubusercontent.com/73477224/157997745-93a9e1e5-dbf3-4a3b-b7c5-40258b8dd7bd.png)

**Comment by Jotiprime** [comment]
![Captura de pantalla 2022-03-12 022320](https://user-images.githubusercontent.com/73477224/157998005-dbf09f47-ae67-4840-a8e0-a00a52bd062d.png)

**Comment by fred4jupiter** [comment]
With which java version did you try to compile the sources? You need the Java JDK 17 to compile it. The error says "invalid target release". So I think you used on older java version, right?

**Comment by Jotiprime** [comment]
I installed all things following the readme, but I know that java versions are different, I tried to fix, but I don't know how to doit (I think that the error is with java path) But at the end I used Docker, and all works perfect, the only thing is that is for amd64 and I have arm64, so if you can upload to docker the arm version, I will really appreciate. Thanks!

**Comment by fred4jupiter** [comment]
You can check with 'java version' if you have the correct version configured in path. Currently I have no arm system to create a docker image for the arm architecture. I will put it on the roadmap to provide such an image

**Comment by Jotiprime** [comment]
You can make the arm image with oracle cloud (free arm machine) https://www.youtube.com/watch?v=TCwwTZPGCbo

If you can make the docker image for arm, I will appreciate, since with my solution, there is no option to edit any file, so if I want to make a change, I have to rebuild all the system.

**Comment by Jotiprime** [comment]
> You can check with 'java version' if you have the correct version configured in path. Currently I have no arm system to create a docker image for the arm architecture. I will put it on the roadmap to provide such an image

**Comment by fred4jupiter** [comment]
> You can make the arm image with oracle cloud (free arm machine)
Yes, I now. But you have to setup a machine which uses the ARM architecture to build an ARM image. Another option was to use the docker buildx but I´ve not tested it before.

What about using a cloud instance with amd64? Why do you need an ARM docker image?

**Comment by Jotiprime** [comment]
I'm not using a cloud instance, I'm using my server that is build in arm, the instance is a solution for you since you don't have an arm machine.

**Comment by fred4jupiter** [comment]
I will close this issue because its not a java error. OK?

**Comment by Jotiprime** [comment]
ok

**Comment by fred4jupiter** [comment]
Closing the issue, because its not a Java error.
