### ISSUE TITLE
Support languages spanish and catalan

### ISSUE THREAD

**Issue by Jotiprime** [fred4jupiter/fredbet#32]
Hey Fred4jupiter, can you open me in Twitter? I have the translations of fredbet for Spanish and catalan. Also I will appreciate you if you build the docker container with arm64. I made it  with docker build --platform=linux/arm64 command, but then when I enter to the docker console, to see the files, there is no option to edit any file, so if I want to edit one message or something, I have to build the container another time. Any solution?

Thanks!

**Comment by fred4jupiter** [comment]
Hi Jotiprime. Please create a merge request for the i18n translations. I will have a look if it works. 
I will also check if I can create a docker image for arm64.

**Comment by Jotiprime** [comment]
How can I create a merge? Can I just upload here the two messages files? (you will need to include the languages in _navigation.html)

**Comment by Jotiprime** [comment]
> Hi Jotiprime. Please create a merge request for the i18n translations. I will have a look if it works. I will also check if I can create a docker image for arm64.

Can you make the arm image dor now? I need to change some things and for me is horrible to edit, upload and have to compile all the time the container and start the container and then upload the database. I don't know why with my compilation (docker build --platform=linux/arm64 command) there is no option to edit anything, in docker console, there not appear the app folder with the files. So I really appreciate if you compile the container.

**Comment by Jotiprime** [comment]
What command and file you used to build the image?

**Comment by fred4jupiter** [comment]
About the languages: You can create a new branch where you add your translations. Then you push the branch and create a merge request. If you are not familiar with GIT then you can upload the files as a comment in this issue. I will have a look.

About the ARM docker image: I did not create an ARM docker image yet. So I also have to investigate some time. Currently I´m very busy. Best option will be a multi arch build with a Gihub action but I will see.

**Comment by Jotiprime** [comment]
When I use this image (https://hub.docker.com/r/fred4jupiter/fredbet), in root directory of the docker container appears this folder called app, inside the resources and I can edit for example the messages.properties without need of rebuild the image.

![Captura de pantalla 2022-03-15 170355](https://user-images.githubusercontent.com/73477224/158420651-c43c9040-3bff-4482-8816-8bab349d2581.png)

**Comment by Jotiprime** [comment]
When I use this image (https://hub.docker.com/r/fred4jupiter/fredbet)  **LATEST image**

So if you can give me the same files / instructions that you use when you build this image it will be helpful.

**Comment by fred4jupiter** [comment]
You can find these files in the source under https://github.com/fred4jupiter/fredbet/tree/master/src/main/resources.
For translations into another language you have to provide translations of the ValidationMessages.properties and messages.properties. You can check out the source with GIT or download the complete repo with https://github.com/fred4jupiter/fredbet/archive/refs/heads/master.zip

**Comment by fred4jupiter** [comment]
I´ve created an ARM docker image build within Github workflow. Can you please check if this image is running on your ARM machine? 
`docker pull fred4jupiter/fredbet:2-arm64`

**Comment by Jotiprime** [comment]
? Do you know why? or how can I make that app directory appears in arm?

**Comment by fred4jupiter** [comment]
Its currently a build which uses a fat jar. The complete application is within the fredbet.jar file. Please send me the translations and I will integrate them.

**Comment by Jotiprime** [comment]
Here you have the messages (there are in .xtx because I can't upload a .properties file in github)

Spanish:

[messages_es.properties.txt](https://github.com/fred4jupiter/fredbet/files/8268301/messages_es.properties.txt)


Catalan:


[messages_ca.properties.txt](https://github.com/fred4jupiter/fredbet/files/8268304/messages_ca.properties.txt)

**Comment by Jotiprime** [comment]
> Its currently a build which uses a fat jar. The complete application is within the fredbet.jar file. Please send me the translations and I will integrate them.

Can you make me a arm64 image with this fat jar, so I can have the app directory / folder?? If not, you can pass me the files and  I will make.

**Comment by Jotiprime** [comment]
Can you make me a arm64 image with this fat jar, so I can have the app directory / folder?? If not, you can pass me the files and I will make.

**Comment by Jotiprime** [comment]
> Its currently a build which uses a fat jar. The complete application is within the fredbet.jar file. Please send me the translations and I will integrate them.

Fred, Please, can you make me a arm64 image with this fat jar, so I can have the app directory / folder?? If not, you can pass me the files and I will make.

**Comment by fred4jupiter** [comment]
Thanks for the translations. Can you also translate the ValidationMessages? They are also needed. I will then add these languages to the app than a user can switch between all languages. After that the docker images will be automatically rebuild.

**Comment by fred4jupiter** [comment]
All files are checked in. You can fork the repo and change files to your needs.

**Comment by Jotiprime** [comment]
[ValidationMessages_ca.txt](https://github.com/fred4jupiter/fredbet/files/8292517/ValidationMessages_ca.txt)
[ValidationMessages_es.txt](https://github.com/fred4jupiter/fredbet/files/8292518/ValidationMessages_es.txt)

**Comment by Jotiprime** [comment]
Can you make the image with the app directory/folder?????

**Comment by fred4jupiter** [comment]
No. I cannot create the arm image with app folder. There is also no option to edit the files as live reload. You can start the app as classic Spring Boot App before building the image. The messages will be loaded once at boot time.

**Comment by Jotiprime** [comment]
Okay, thanks, Can you do this please?

Add an option to put a background image in each (including login and register) page (optionn to put diferent image in different page) from config.
Also a option to change the menu bar color from config.

**Comment by fred4jupiter** [comment]
Please do not mix up different issues within one. For new topics please open another issue for that.

I will check the translations, but this will take some time (days). I will give feedback.

**Comment by Jotiprime** [comment]
Okay!

**Comment by fred4jupiter** [comment]
I´ve integrated the languages. Please check the latest version.

**Comment by fred4jupiter** [comment]
The languages are now included in the latest version. So I will close this issue.
