### ISSUE TITLE
Change background and navigation bar color in runtime configuration

### ISSUE THREAD

**Issue by Jotiprime** [fred4jupiter/fredbet#33]
Hey, Can you add an option to put a background image in each (including login and register) page (optionn to put diferent image in different page) from config.
Also a option to change the menu bar color from config.

Thanks!

**Comment by fred4jupiter** [comment]
That sounds very weird to me. It slows down the loading time of a page, especially on mobile devices. So what is your use case for this?

**Comment by Jotiprime** [comment]
For friends, but I like a little customization like background and colors.

**Comment by fred4jupiter** [comment]
I´ve integrated the bootswatch library for using multiple themes within FredBet. You can switch the theme and the navbar (default and inverse) for best look and feel. See latest docker image. An offical release will follow soon.

**Comment by Jotiprime** [comment]
Okay, Thanks!!
