### ISSUE TITLE
Favicon not showing until you are logged in.

### ISSUE THREAD

**Issue by Jotiprime** [fred4jupiter/fredbet#35]
Favicon not showing until you are logged in, can you make it always show?

**Comment by fred4jupiter** [comment]
It should not be visible. Please check the latest version.

**Comment by Jotiprime** [comment]
But I want to be visible!

**Comment by fred4jupiter** [comment]
Ah, sorry for the typo. It show NOW be visible.

**Comment by fred4jupiter** [comment]
Should be resolved with latest version
