### ISSUE TITLE
docker-compose for mariadb, "Bonus bets" issue

### ISSUE THREAD

**Issue by pkovi** [fred4jupiter/fredbet#39]
The world cup is coming
Your application is exactly what I was looking for, it fulfills all my ideas. Excellent work!

However, I have one problem. I am trying used the docker version  docker-compose.yml for Mariadb. I have problem with screen "Bonus bets"  (the champion,vicechampion... ). The SAVE button is missing on the screen, so the tip cannot be saved. Instead SAVE button there is only link "[... these are bets of the others]"

If I start the container with the command
docker run -d -p 8080:8080 fred4jupiter/fredbet
everything is OK.

**Comment by fred4jupiter** [comment]
Hi Pkovi. In the bonus tips screen the save button will disappear if the first match of the championship has started. In other words: you have to do all of your bonus tips before the championship starts. After the first match has begun you can see the tips of the other players and can´t change your bonus tips anymore. So this is intended.

**Comment by pkovi** [comment]
Hi, thank you for the explanation, it is exactly as you wrote.
There is no connection with Mariadb.
At first I tried other featutures of  application and when I got to this option I already had some games played.
Thank you very much
GREAT!!
