### ISSUE TITLE
Howto delete Matches?

### ISSUE THREAD

**Issue by sunnybeats** [fred4jupiter/fredbet#41]
Hey and thanks for this great Product!
I just love to use it.
But I have a little problem.
While manually creating matches i made a mistake and created the same match 2 times.
Is there any way in the webui to delete the one i created by mistake?
If not, could you add this feature in future?

Thanks a lot!

**Comment by sunnybeats** [comment]
PS: in meinem Fall ist auch auf deutsch ok :)

**Comment by fred4jupiter** [comment]
Hi sunnybeats,
yes, of course you can delete a match unless someone gives a bet for it. After that it is not possible anymore.
You have to login as admin, click on match "edit" and there you can see a red button "delete".
Is this sufficient for your use case?
Best regards,
Michael

**Comment by sunnybeats** [comment]
Ah ok so i blocked myself by betting it.
So you can close this issue.
Ich will open a new one for another question.
Bit its more Feature request. You will see.

Thanks a lot!

**Comment by fred4jupiter** [comment]
OK, great. I will close this ticket.
