### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sunnybeats** [fred4jupiter/fredbet#42]
Hey its me again.
There is one idea gor the future.
Is it possible to create a detting to disable the photo upload or set a limit "pool size"

Because in theory somebody could overload my server with picture.

Especially if i enable the self register function.

Thanks :)

**Comment by fred4jupiter** [comment]
Hi, I could think of a user limit for uploading photos. Generally you should "know" your user, because you (or the admin) created them or they self register with a given registration code you gave to them.

**Comment by fred4jupiter** [comment]
I added the possibility to limit the number of photo uploads per user. Please see latest docker tag (tag "latest").

**Comment by sunnybeats** [comment]
Hey,
Thanks for the fast patch.
I already updated my container hope the build version 3.0.2 in Systeminfo of the webui is right.

But i wasnr able to find the option yet.
I looked in Admin/user and Admin/Configuration for it.

Am i looking at the wrong places?

Thanks a lot!

**Comment by fred4jupiter** [comment]
Version 3.0.2 is not released yet. I mean the "latest" tag in docker:

`docker run -d -p 8080:8080 fred4jupiter/fredbet:latest`

**Comment by sunnybeats** [comment]
I tried it wirh a new container instead of updating my existing one and ir works!

So it was my fault in the update process. Sorry.

**Comment by fred4jupiter** [comment]
Just released version 3.1.0 where this feature is included. So I will close this issue.
