### ISSUE TITLE
[Enhancement] Own bonus tips and some other Stuff

### ISSUE THREAD

**Issue by J000K3R** [fred4jupiter/fredbet#46]
I would think it would be great if we had our own bonus tips or more ready-made ones like in other similar prediction games.
However, these should only refer to the countries and not to players or others.
Here are a few examples:

- Which teams will reach the semi-finals?
- Which team will score the fewest goals?
- Which team scores the most goals?
- Which country is the top scorer?
- Which team concedes the most goals?

------------------------------------------------------------------------------------------------

The following functions would also be useful:

Set a deadline: How many minutes before kick-off can bets still be submitted?

Matchday winner: Which player has scored the most points on today's matchday. This could possibly also be included in the overall ranking.

A news page where the admin can post individual entries and players can comment on them.

**Comment by fred4jupiter** [comment]
Hi J000K3R, thanks for you ideas! Currently there is no plan to support more bonus tips. But that may change in the future. Therefore I keep this issue open for now.

>> Set a deadline: How many minutes before kick-off can bets still be submitted?

Currently all users can change their bets if the match has not yet been started. I  think there is no need to limit this setting.

>> Matchday winner: Which player has scored the most points on today's matchday. This could possibly also be included in the overall ranking.

This sounds reasonable. I will think about this feature. Maybe I can add it in the statstics area.

>> A news page where the admin can post individual entries and players can comment on them.

The "/info/misc" page was intended for sharing news and other kind of stuff. Everyone can edit it.

**Comment by J000K3R** [comment]
Thanks @fred4jupiter for your reply.
Is it ok for you if I expand my list here if I have a few more points that I notice during the betting game for Euro 2024?

Enclosed I have created a few logos with Stable Difussion which you can use as a logo if you like.
I also wanted to ask you if it is ok if I create a Unraid template so that others from the Unraid community can use this Docker.

Thank you very much for your work and effort and keep up the good work.
![00007-2079149212](https://github.com/fred4jupiter/fredbet/assets/60364963/eeeab5c2-1945-4b9f-a19c-b1439e0a1e3c)
![00009-3629651398](https://github.com/fred4jupiter/fredbet/assets/60364963/255034c2-428f-4f1a-b1f1-05da10297265)
![00007-1483015506](https://github.com/fred4jupiter/fredbet/assets/60364963/eb002a2a-439b-4317-9c1e-d126d1eec097)
![00051-3421757725](https://github.com/fred4jupiter/fredbet/assets/60364963/cd29bf3c-ce5a-4e6a-882e-b905281298d3)
![00005-3421757696](https://github.com/fred4jupiter/fredbet/assets/60364963/7549f37c-8c30-45e8-8b92-ccf8719c362f)
![00004-3478227189](https://github.com/fred4jupiter/fredbet/assets/60364963/365ff058-18a0-4c71-83e4-8760bd46407f)
![00003-210913040](https://github.com/fred4jupiter/fredbet/assets/60364963/2fce868d-27d4-4229-8f4b-25e75081bf6f)
![00002-1791180318](https://github.com/fred4jupiter/fredbet/assets/60364963/8c037318-aa1f-4063-8aa1-f5a61410860b)
![00001-501575437](https://github.com/fred4jupiter/fredbet/assets/60364963/99973a01-2fb5-4f0c-ab55-804a906bfc72)
![00010-2473634740](https://github.com/fred4jupiter/fredbet/assets/60364963/6f7ca665-341d-4355-b599-eaa5ec4bc6ae)
![00009-2255185891](https://github.com/fred4jupiter/fredbet/assets/60364963/b7ba966b-ea0e-4731-8920-60fa5df14bdf)
![00008-2644302823](https://github.com/fred4jupiter/fredbet/assets/60364963/3cb85746-4a88-4589-8a2b-4d9d689f0795)

**Comment by J000K3R** [comment]
Sorry just closed the Issue..

**Comment by fred4jupiter** [comment]
> Is it ok for you if I expand my list here if I have a few more points that I notice during the betting game for Euro 2024?

Yes, your feedback is welcome! :-)

> I also wanted to ask you if it is ok if I create a Unraid template so that others from the Unraid community can use this Docker.

Yes, of course.

**Comment by fred4jupiter** [comment]
I've just implemented the "Matchday winner". That was a "low hanging fruit". 
![matchday_winner](https://github.com/fred4jupiter/fredbet/assets/1114344/6a38c09b-d6f1-4e45-9ade-db7d2c3cc6a0)
I will be displayed in the ranking list.

**Comment by J000K3R** [comment]
> I've just implemented the "Matchday winner". That was a "low hanging fruit". ![matchday_winner](https://private-user-images.githubusercontent.com/1114344/335626675-6a38c09b-d6f1-4e45-9ade-db7d2c3cc6a0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjk2NzIsIm5iZiI6MTcxNzE2OTM3MiwicGF0aCI6Ii8xMTE0MzQ0LzMzNTYyNjY3NS02YTM4YzA5Yi1kNmYxLTRlNDUtOWFkZS1kYjdkMmMzY2M2YTAuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MzFUMTUyOTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Yzk2MDFjZGVlZTNjNjg3NzQyZDAzYjA5ZTlmMmY1NGU4ZWJlNDU0MzFjYzE3ZWZkN2ZkMjczNzA1MjVjODNhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.k6RBzvADY9-Ed5WukyjOuvzz2g-8qpjegsusq8Mh0VA) It will be displayed in the ranking list.

Awesome Thanks !!

**Comment by J000K3R** [comment]
The new update is great with the API integration.

Some good additions would be:

- A chat feature for all members to communicate with each other
- A feature to customize the login page, such as the title
- A news page where the admin can post announcements or send emails
- A countdown to the next match

**Comment by fred4jupiter** [comment]
You can customize the login page with your own image. I also thought about a chat function but there are enough apps out there everyone is still using. The info misc page was the intention to share informations as anybody can edit this page.
