### ISSUE TITLE
bonus bet for 3rd winner missing

### ISSUE THREAD

**Issue by reinhardgilles** [fred4jupiter/fredbet#48]
Hi, great project.

I can configure points for the 3rd winner but on the page for bonus bets only champion and vice champion can be selected.

**Comment by fred4jupiter** [comment]
This belongs to the "game of third" or "3rd playoff match". In the upcoming european championship 2024 there is no "game of third" (the group of the match has to be "Gameof Third"). So in this case you can ignore the 3rd winner bonus points configuration.
