### ISSUE TITLE
Bets are not visible after export and import all data in new app version

### ISSUE THREAD

**Issue by bartektartanus** [fred4jupiter/fredbet#50]
I wanted to update version 3.3.0 to 3.3.1, so I've exported all the data to json and then imported it onto new app. All the scores are correct, but bets are not visible.
<img width="386" alt="image" src="https://github.com/fred4jupiter/fredbet/assets/3193882/8010151b-f20a-4e8a-8c13-3e6e6f98f288">

**Comment by fred4jupiter** [comment]
Yes, I can reproduce the error. The bets will not be imported by now. I will try to fix that soon.

As a workaround you can backup your database and upgrade to the new image version 3.3.1. This is just a bugfix release. So import and export for this use case is not necessary.

**Comment by fred4jupiter** [comment]
fixed with version 3.3.2

Note: Both containers (import and export side) has to run in version 3.3.2
