### ISSUE TITLE
Avatars lost when importing using JSON

### ISSUE THREAD

**Issue by lars-devs** [fred4jupiter/fredbet#52]
Hi, first kudos to you for the great project and the EM template!

I just found out that importing using the JSON results in loss of avatars. Since the exported JSON doesn't include images and I agree it would break the single file approach if images would be included, I do think that avatars should be kept if the JSON to be imported includes existing users with avatars already uploaded.

Greets 
Lars

**Comment by fred4jupiter** [comment]
Avatars are not included in Json export, thats right. I will leave this ticket open as a feature request to be included in the future. 
Greets, Michael

**Comment by fred4jupiter** [comment]
Hi Lars, 
I have integrated user profile image (avatars) in JSON export and import. Please check the "latest" tag of the docker image. 

Greets,
Michael

**Comment by lars-devs** [comment]
Hi Michael,

amazing, works like a charm! Thanks.

Regards,
Lars
